FROM python:3.8.3-slim-buster

RUN apt-get update && \
    apt-get install -y gcc make git bash curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
	pip install pylint

ENTRYPOINT ["pylint", "--version"]
